name: "setup-atopile"
description: "Setup atopile CLI"
branding:
  icon: "package"
  color: "orange"

inputs:
  ato-config:
    description: 'Path to ato.yaml config, based on which to determine the version to run'
    required: false
    default: ""
  version:
    description: 'A specific version of atopile to use'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        pyproject-file: "${{ github.action_path }}/pyproject.toml"

    - id: determine-atopile-version
      run: uv run --project "${{ github.action_path }}" python "${{ github.action_path }}/main.py" >> $GITHUB_OUTPUT
      shell: bash
      env:
        ATO_CONFIG: ${{ inputs.ato-config }}
        SPECIFIED_VERSION: ${{ inputs.version }}

    - name: Pull atopile container
      run: >
        docker pull
        "ghcr.io/atopile/atopile-kicad:${{ steps.determine-atopile-version.outputs.version }}"
      shell: bash

    - name: Tag atopile container
      run: >
        docker tag
        "ghcr.io/atopile/atopile-kicad:${{ steps.determine-atopile-version.outputs.version }}"
        "atopile-local"
      shell: bash

    - name: Install alias
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
      shell: bash
