[project]
name = "run-atopile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ruamel-yaml>=0.18.10",
    "semver>=3.0.4",
]

[tool.uv]
required-version = ">=0.6.14,<0.7.0"
